---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "192.168.30.15"
    vcenter_user: "Administrator@vsphere.local"
    vcenter_pass: "Datamato@123"
    datacenter_name: "Datamato"
    #    cluster_name: "Cluster"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ 'test_vm%03d' | format(item) }}"
      template: DM-CENTOS
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      #      cluster: "{{ cluster_name }}"
      resource_pool: resourcepool_dm
      datastore: "datastore1"
      #     disk:
      #- size_gb: 50
      # type: thin
      # datastore: "datastore1"
      hardware:
        memory_mb: 1024
        num_cpus: 1
        # networks:
        #- name: VM Network
        #ip: 192.168.30.220
        #netmask: 255.255.255.0
        #gateway: 192.168.30.1
        #type: static
        #dns_servers:
        #- 192.168.30.1
        #- 192.168.30.2
        # customization:
        # hostname: "web01"
        # dns_servers:
        # - 192.168.30.1
        # - 192.168.30.2
        #- 1.1.1.1
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
    loop: "{{ range(0, 5, 1) | list }}"
